version: "3.8"

services:
  nginx:
    image: nginx:seonjo
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp-vol:/var/www/html
    networks:
      - intra
    init: true
  wordpress:
    image: wordpress:seonjo
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp-vol:/var/www/html
    expose: 
      - "9000"
    networks:
      - intra
    init: true
  mariadb:
    image: mariadb:seonjo
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - db-vol:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - intra
    init: true

volumes:
  wp-vol:
    name: wp-vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seonjo/data/wp
  db-vol:
    name: db-vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seonjo/data/db

networks:
  intra:
    name: intra
    driver: bridge