version: '3'

services:
	mariadb:
		image: mariadb
		build:
			context: ./requirements/mariadb/
			dockerfile: Dockerfile
		restart: always
		expose:
			- "3306"
		networks:
			- intra
		init: true
		#tty: true
	nginx:
		image: nginx
		build:
			context: ./requirements/nginx/
			dockerfile: Dockerfile
		restart: always
		ports:
			- "443:443"
		#volumes:
			#- data:/var/www/html
		networks:
			- intra
		init: true
		#tty: true
	wordpress:
		image: wordpress
		build:
			context: ./requirements/wordpress/
			dockerfile: Dockerfile
		restart: always
		#volumes:
			#- data:/var/www/html
		expose: 
			- "9000"
		networks:
			- intra
		init: true
		#tty: true

#volumes:
	#data: {}

networks:
	intra:
		driver: bridge