version: "3.8"

services:
  nginx:
    image: nginx:seonjo
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - vol:/var/www/html
    networks:
      - intra
    init: true
  wordpress:
    image: wordpress:seonjo
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes:
      - vol:/var/www/html
    expose: 
      - "9000"
    networks:
      - intra
    init: true

volumes:
  vol:

networks:
  intra:
    driver: bridge