version: '3'

services:
    nginx:
        image: nginx
        container_name: nginx
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        restart: always
        ports:
            - "443:443"
        volumes:
            - vol:/var/www/html
        networks:
            - intra
        init: true
    wordpress:
        image: wordpress
        container_name: wordpress
        build:
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        restart: always
        volumes:
            - vol:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        init: true

volumes:
    vol:

networks:
    intra:
        driver: bridge